## Gemini Model

In [14]:
from autogen_core.models import UserMessage
from autogen_ext.models.openai import OpenAIChatCompletionClient
import os
from dotenv import load_dotenv
from autogen_agentchat.agents import AssistantAgent

In [7]:
load_dotenv()

True

In [3]:
from autogen_core.models import UserMessage
from autogen_ext.models.openai import OpenAIChatCompletionClient

model_client = OpenAIChatCompletionClient(
    model="gemini-1.5-flash-8b",
    api_key=os.getenv("GOOGLE_API_KEY"),
)

response = await model_client.create([UserMessage(content="What is the capital of India?", source="user")])
print(response)
await model_client.close()


finish_reason='stop' content='New Delhi\n' usage=RequestUsage(prompt_tokens=7, completion_tokens=3) cached=False logprobs=None thought=None


## OpenRouter Model

In [ ]:
open_router_api_key = os.getenv("OPEN_ROUTER_KEY")

open_router_model_client =  OpenAIChatCompletionClient(
    base_url="https://openrouter.ai/api/v1",
    model="deepseek/deepseek-chat-v3-0324:free",
    api_key = open_router_api_key,
    model_info={
        "family":'deepseek',
        "vision" :True,
        "function_calling":True,
        "json_output": False
    }
)

finish_reason='stop' content='The capital of France is **Paris**. \n\nParis is one of the most famous cities in the world, known for its rich history, iconic landmarks like the **Eiffel Tower**, **Louvre Museum**, and **Notre-Dame Cathedral**, as well as its cultural influence in art, fashion, and cuisine. Would you like more details about Paris or France in general?' usage=RequestUsage(prompt_tokens=12, completion_tokens=78) cached=False logprobs=None thought=None


### Way 1

In [12]:
response = await open_router_model_client.create([UserMessage(content="What is the capital of France?", source="user")])

print(response)

finish_reason='stop' content='The capital of France is **Paris**.  \n\nParis is known for its iconic landmarks such as the Eiffel Tower, the Louvre Museum, and the Arc de Triomphe. It is also a major cultural, political, and economic hub of Europe.  \n\nWould you like any additional details about Paris or France?' usage=RequestUsage(prompt_tokens=12, completion_tokens=64) cached=False logprobs=None thought=None


### Way 2

In [15]:
agent=AssistantAgent(name="OpenRouterAssistant", model_client=open_router_model_client)
result1 = await agent.run(task="What is the capital of France?")
print(result1)

messages=[TextMessage(id='dc83b4e3-ef0a-486f-8eb8-ca5133882fb7', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 11, 14, 53, 27, 753106, tzinfo=datetime.timezone.utc), content='What is the capital of France?', type='TextMessage'), TextMessage(id='5dfbd546-299a-482d-93b1-0128e899406c', source='OpenRouterAssistant', models_usage=RequestUsage(prompt_tokens=37, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 8, 11, 14, 53, 30, 146804, tzinfo=datetime.timezone.utc), content='The capital of France is Paris. \n\nTERMINATE', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='dc83b4e3-ef0a-486f-8eb8-ca5133882fb7', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 11, 14, 53, 27, 753106, tzinfo=datetime.timezone.utc), content='What is the capital of France?', type='TextMessage'), TextMessage(id='5dfbd546-299a-482d-93b1-0128e899406c', source='OpenRouterAssistant', models_usage=RequestUsage(prompt_tokens=37, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 8, 11, 14, 53, 30, 146804, tzinfo=datetime.timezone.utc), content='The capital of France is Paris. \n\nTERMINATE', type='TextMessage')] stop_reason=None